### ISSUE TITLE
Why React?

### ISSUE THREAD

**Issue by arvindpdmn** [taniarascia/react-tutorial#1]
You have answered What is React? But Why should I adopt React? Why was it invented? What problem does it solve? This will be useful info. Thx

**Comment by nkhil** [comment]
There's some good discussion here about why you'd use something like React: https://dev.to/mraza007/why-use-react-instead-of-javascript-html-and-css-55hh

**Comment by arvindpdmn** [comment]
Actually we created a separate article to answer this question but particular to React Native: https://devopedia.org/react-native
