### ISSUE TITLE
removechracter shows not a function while clicking delete button

### ISSUE THREAD

**Issue by naveenrajrk** [taniarascia/react-tutorial#18]
TypeError: props.removecharacter is not a function
onClick
C:/Users/naveen raj rk/Desktop/new2/mydemoapp/src/Table.js:22

  19 |    <td>{row.name}</td>
  20 |    <td>{row.job}</td>
  21 |    <td>
> 22 |    <Button onClick={()=>props.removecharacter(index)}>Delete</Button>
     | ^  23 |    </td>
  24 |    </tr>
  25 | );

**Comment by taniarascia** [comment]
It should probably be `removeCharacter`.
