### ISSUE TITLE
Question  eslint issue in tutorial section state https://www.taniarascia.com/getting-started-with-react/

### ISSUE THREAD

**Issue by ncjohnson6318** [taniarascia/react-tutorial#4]
I am getting an error with the unexpected token in the section about State.   It has to do with jslint and '<'
in the return (<   .   Can you help configure this?   
![2019-02-28 14_07_42-npm](https://user-images.githubusercontent.com/41207415/53591609-6b078700-3b62-11e9-948d-673d38fa6a4b.png)

**Comment by taniarascia** [comment]
I don't know how you installed this, but it's supposed to be inside of a `create-react-app` project. If you simply forked the repo and tried to run it standalone, it will not work.
